from app.api.routes import (
    algorithms,
    analytics,
    announcements,
    auth,
    chat,
    college_documents,
    community,
    dashboard,
    documents,
    gamification,
    interviews,
    jobs,
    quizzes,
    resume,
    skills,
    subjects,
)

__all__ = [
    "algorithms",
    "analytics",
    "announcements",
    "auth",
    "chat",
    "college_documents",
    "community",
    "dashboard",
    "documents",
    "gamification",
    "interviews",
    "jobs",
    "quizzes",
    "resume",
    "skills",
    "subjects",
]
