"""Model package for Alembic autogenerate discovery.

All models must be imported here so Alembic picks them up during `revision --autogenerate`.
"""

from app.core.database import Base
from app.models.algorithm import (
    CompanySkillRequirement,
    NotificationDelivery,
    NotificationStatus,
    NotificationType,
    QuizSimilarityFlag,
    QuizTimeSlot,
    SkillGraphEdge,
    SkillNode,
    StudyOptimizerResult,
    WeeklySchedule,
)
from app.models.chat import ChatMessage, ChatSession, ChatType, MessageRole
from app.models.coding import (
    CodingDifficulty,
    CodingLanguage,
    CodingPattern,
    CodingProblem,
    CodingSubmission,
    CodingSubmissionStatus,
)
from app.models.community import Doubt, DoubtAnswer
from app.models.content import (
    Announcement,
    AnnouncementTarget,
    CollegeDocument,
    CollegeDocumentCategory,
    CollegeDocumentChunk,
    DocumentChunk,
)
from app.models.gamification import (
    Badge,
    CampusIQScore,
    Challenge,
    ChallengeEntry,
    ChallengeType,
    SkillTreeProgress,
    XPEvent,
    XPEventType,
)
from app.models.grading import (
    AnswerSheet,
    AnswerSheetStatus,
    CourseOutcome,
    Exam,
    ExamKind,
    ExamPart,
    ExamQuestion,
    ExamResult,
    GateFailure,
    LetterGrade,
    Leniency,
    QuestionGrade,
    ResultSource,
    SchemeStatus,
    SemesterResult,
    SubjectGrade,
    SubjectGradeConfig,
)
from app.models.placement import (
    ApplicationStatus,
    ConfidenceSession,
    InterviewMode,
    InterviewPersona,
    InterviewStatus,
    JobApplication,
    JobListing,
    JobListingSource,
    JobType,
    MockInterviewSession,
    Resume,
)
from app.models.quiz import (
    CIEComponent,
    Difficulty,
    Question,
    QuestionType,
    Quiz,
    QuizAttempt,
    QuizMode,
)
from app.models.user import (
    College,
    Document,
    DocumentStatus,
    StudentProfile,
    Subject,
    SubjectCategory,
    SubjectEnrollment,
    TeacherProfile,
    User,
    UserRole,
)

__all__ = [
    "Base",
    # Users
    "College",
    "User",
    "UserRole",
    "StudentProfile",
    "TeacherProfile",
    "Subject",
    "SubjectCategory",
    "SubjectEnrollment",
    "Document",
    "DocumentStatus",
    # Content
    "DocumentChunk",
    "CollegeDocument",
    "CollegeDocumentCategory",
    "CollegeDocumentChunk",
    "Announcement",
    "AnnouncementTarget",
    # Chat
    "ChatSession",
    "ChatMessage",
    "ChatType",
    "MessageRole",
    # Coding (V1 platform)
    "CodingPattern",
    "CodingProblem",
    "CodingSubmission",
    "CodingDifficulty",
    "CodingLanguage",
    "CodingSubmissionStatus",
    # Quiz
    "Quiz",
    "Question",
    "QuizAttempt",
    "Difficulty",
    "QuestionType",
    "QuizMode",
    "CIEComponent",
    # Grading (AI auto-grader + grade engine)
    "CourseOutcome",
    "SubjectGradeConfig",
    "Exam",
    "ExamQuestion",
    "AnswerSheet",
    "QuestionGrade",
    "ExamResult",
    "SubjectGrade",
    "SemesterResult",
    "ExamKind",
    "ExamPart",
    "Leniency",
    "SchemeStatus",
    "AnswerSheetStatus",
    "ResultSource",
    "LetterGrade",
    "GateFailure",
    # Community
    "Doubt",
    "DoubtAnswer",
    # Placement
    "Resume",
    "MockInterviewSession",
    "ConfidenceSession",
    "JobListing",
    "JobApplication",
    "InterviewMode",
    "InterviewPersona",
    "InterviewStatus",
    "JobType",
    "JobListingSource",
    "ApplicationStatus",
    # Gamification
    "XPEvent",
    "XPEventType",
    "SkillTreeProgress",
    "Badge",
    "Challenge",
    "ChallengeEntry",
    "ChallengeType",
    "CampusIQScore",
    # Algorithm features
    "SkillGraphEdge",
    "SkillNode",
    "CompanySkillRequirement",
    "StudyOptimizerResult",
    "NotificationDelivery",
    "NotificationType",
    "NotificationStatus",
    "QuizSimilarityFlag",
    "WeeklySchedule",
    "QuizTimeSlot",
]
