"""Pydantic schemas for request/response validation."""

from app.schemas.analytics import (
    AnalyticsHeadline,
    ClassAnalytics,
    ScoreBucket,
    StudentPerformanceRow,
    TrendLiteral,
    WeakTopicRow,
)
from app.schemas.announcement import (
    AnnouncementCreate,
    AnnouncementResponse,
    AnnouncementTargetLiteral,
    AnnouncementUpdate,
)
from app.schemas.auth import (
    LoginRequest,
    SignupRequest,
    StudentProfileResponse,
    TeacherProfileResponse,
    TokenResponse,
    UserResponse,
)
from app.schemas.chat import (
    ChatMessageRequest,
    ChatMessageResponse,
    ChatSessionCreate,
    ChatSessionResponse,
    ChatSessionWithMessages,
    ChatTypeLiteral,
    MessageRoleLiteral,
    SourceCitation,
)
from app.schemas.college_document import (
    CollegeDocumentCategoryLiteral,
    CollegeDocumentChunkPreview,
    CollegeDocumentCreateMetadata,
    CollegeDocumentResponse,
    CollegeDocumentStatusLiteral,
)
from app.schemas.dashboard import (
    ActivityItem,
    CampusIQScoreBreakdown,
    DashboardResponse,
    DashboardStats,
    TaskItemResponse,
    TaskKindLiteral,
    TaskPriorityLiteral,
    XPProgress,
)
from app.schemas.document import (
    CompressionStats,
    DocumentChunkPreview,
    DocumentCreateMetadata,
    DocumentResponse,
    DocumentStatusLiteral,
    DocumentWithSubject,
    SemanticSearchHit,
    SemanticSearchRequest,
    SemanticSearchResponse,
)
from app.schemas.quiz import (
    AttemptHistoryRow,
    DifficultyLiteral,
    GradedAnswer,
    QuestionAnswer,
    QuestionStudentView,
    QuestionTeacherView,
    QuestionTypeLiteral,
    QuestionUpdate,
    QuizAttemptCreate,
    QuizAttemptResponse,
    QuizForStudent,
    QuizForTeacher,
    QuizGenerateRequest,
    QuizResponse,
    QuizUpdate,
    WeakAreaResponse,
)
from app.schemas.mock_interview import (
    InterviewMessageRequest,
    InterviewModeLiteral,
    InterviewPersonaLiteral,
    InterviewSessionListRow,
    InterviewSessionResponse,
    InterviewStartRequest,
    InterviewStatusLiteral,
    InterviewTranscriptTurn,
    InterviewTurnResponse,
    RoundSummary,
    ROUND_NAMES,
)
from app.schemas.resume import (
    ATSScoreRequest,
    ATSScoreResponse,
    GitHubImportRequest,
    GitHubImportResponse,
    GitHubProjectImport,
    ResumeChatHistory,
    ResumeChatHistoryItem,
    ResumeChatRequest,
    ResumeChatResponse,
    ResumeContent,
    ResumeContentUpdate,
    ResumeEducation,
    ResumeExperience,
    ResumePersonal,
    ResumeProject,
    ResumeResponse,
    ResumeTemplateLiteral,
)
from app.schemas.skills import (
    AdaptivePlanRequest,
    AdaptivePlanResponse,
    CompanyProfile,
    GapBreakdownResponse,
    KnapsackItemResponse,
    KnapsackResponse,
    MasteryItem,
    MasterySnapshotResponse,
    MSTEdge,
    MSTResponse,
    PathEdge,
    SkillEdgeResponse,
    SkillNodeResponse,
    SkillPathResult,
    StudyOptimizerHistoryRow,
)
from app.schemas.subject import SubjectCreate, SubjectResponse, SubjectUpdate

__all__ = [
    # Auth
    "LoginRequest",
    "SignupRequest",
    "StudentProfileResponse",
    "TeacherProfileResponse",
    "TokenResponse",
    "UserResponse",
    # Subject
    "SubjectCreate",
    "SubjectResponse",
    "SubjectUpdate",
    # Document
    "CompressionStats",
    "DocumentChunkPreview",
    "DocumentCreateMetadata",
    "DocumentResponse",
    "DocumentStatusLiteral",
    "DocumentWithSubject",
    "SemanticSearchHit",
    "SemanticSearchRequest",
    "SemanticSearchResponse",
    # Chat
    "ChatMessageRequest",
    "ChatMessageResponse",
    "ChatSessionCreate",
    "ChatSessionResponse",
    "ChatSessionWithMessages",
    "ChatTypeLiteral",
    "MessageRoleLiteral",
    "SourceCitation",
    # College Document
    "CollegeDocumentCategoryLiteral",
    "CollegeDocumentChunkPreview",
    "CollegeDocumentCreateMetadata",
    "CollegeDocumentResponse",
    "CollegeDocumentStatusLiteral",
    # Dashboard
    "ActivityItem",
    "CampusIQScoreBreakdown",
    "DashboardResponse",
    "DashboardStats",
    "TaskItemResponse",
    "TaskKindLiteral",
    "TaskPriorityLiteral",
    "XPProgress",
    # Quiz
    "AttemptHistoryRow",
    "DifficultyLiteral",
    "GradedAnswer",
    "QuestionAnswer",
    "QuestionStudentView",
    "QuestionTeacherView",
    "QuestionTypeLiteral",
    "QuestionUpdate",
    "QuizAttemptCreate",
    "QuizAttemptResponse",
    "QuizForStudent",
    "QuizForTeacher",
    "QuizGenerateRequest",
    "QuizResponse",
    "QuizUpdate",
    "WeakAreaResponse",
    # Mock Interview
    "InterviewMessageRequest",
    "InterviewModeLiteral",
    "InterviewPersonaLiteral",
    "InterviewSessionListRow",
    "InterviewSessionResponse",
    "InterviewStartRequest",
    "InterviewStatusLiteral",
    "InterviewTranscriptTurn",
    "InterviewTurnResponse",
    "RoundSummary",
    "ROUND_NAMES",
    # Announcement
    "AnnouncementCreate",
    "AnnouncementResponse",
    "AnnouncementTargetLiteral",
    "AnnouncementUpdate",
    # Analytics
    "AnalyticsHeadline",
    "ClassAnalytics",
    "ScoreBucket",
    "StudentPerformanceRow",
    "TrendLiteral",
    "WeakTopicRow",
    # Resume
    "ATSScoreRequest",
    "ATSScoreResponse",
    "GitHubImportRequest",
    "GitHubImportResponse",
    "GitHubProjectImport",
    "ResumeChatHistory",
    "ResumeChatHistoryItem",
    "ResumeChatRequest",
    "ResumeChatResponse",
    "ResumeContent",
    "ResumeContentUpdate",
    "ResumeEducation",
    "ResumeExperience",
    "ResumePersonal",
    "ResumeProject",
    "ResumeResponse",
    "ResumeTemplateLiteral",
]
